version: "3.9"

services:
  webserver:
    build:
      context: ./bin/webserver
    ports:
      - "80:80"
      - "443:443"
    links:
      - mariadb
      - mailhog
    networks:
      - dev-lamp-net
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
  mariadb:
    image: 'mariadb:10.1'
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - dev-lamp-net
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dev-lamp-net
networks:
  dev-lamp-net:
    name: dev-lamp-global-net
